import { useState } from 'react'
import StatusPill from './StatusPill.jsx'

function WeekRow({ week }) {
  const [open, setOpen] = useState(false)

  return (
    <div className="bg-white/[0.035] backdrop-blur-md border border-border rounded-xl overflow-hidden
                     hover:border-borderStrong transition-colors">
      <button
        onClick={() => setOpen((v) => !v)}
        className="w-full flex items-center justify-between px-4 py-3 hover:bg-white/[0.03] transition text-left"
      >
        <span className="text-sm font-mono font-medium">{week.week}</span>
        <div className="flex items-center gap-3">
          <StatusPill status={week.status} />
          <span className="text-textLo text-xs font-mono">{open ? '▲' : '▼'}</span>
        </div>
      </button>

      {open && (
        <div className="px-4 pb-4 pt-1 border-t border-border text-sm">
          {week.status === 'insufficient_history' && (
            <p className="text-textLo">Not enough prior weeks yet to establish a reliable baseline.</p>
          )}

          {week.status === 'normal' && (
            <>
              <p className="text-textLo">Within normal historical range for this entity.</p>
              {week.z_scores && (
                <p className="text-xs text-textLo mt-2 font-mono">
                  Feature z-scores: {JSON.stringify(week.z_scores)}
                </p>
              )}
            </>
          )}

          {week.status === 'flagged' && (
            <>
              <p className="mb-2">
                <span className="font-semibold">Anomaly score: </span>
                <code className="text-xs bg-white/[0.06] px-1.5 py-0.5 rounded font-mono">
                  {week.anomaly_score}
                </code>
              </p>
              <p className="text-textLo mb-2">{week.explanation}</p>
              {week.commit_messages?.length > 0 && (
                <div className="mb-2">
                  <p className="font-semibold mb-1">Commit evidence:</p>
                  <ul className="list-disc list-inside text-textLo space-y-0.5">
                    {week.commit_messages.slice(0, 5).map((m, i) => (
                      <li key={i}>{m}</li>
                    ))}
                  </ul>
                </div>
              )}
              <p className="text-xs text-textLo font-mono">
                Explanation generated by: {week.explanation_backend}
              </p>
            </>
          )}
        </div>
      )}
    </div>
  )
}

export default function WeeklyDetail({ weeks }) {
  return (
    <div>
      <h2 className="text-base font-bold mb-3">Weekly detail</h2>
      <div className="space-y-2">
        {weeks.map((w) => (
          <WeekRow key={w.week} week={w} />
        ))}
      </div>
    </div>
  )
}
