"""report.py — Renders a pipeline result dict into a self-contained HTML report for demos.

All values that originate outside this process — entity_id (user-supplied owner/repo),
commit messages (pulled from GitHub, i.e. written by whoever pushed to that repo), and
LLM-generated explanations — are HTML-escaped before being interpolated into the template.
None of that content is trusted; without escaping, a crafted commit message or repo name
could inject markup/script into the generated report.
"""

import html

HTML_TEMPLATE = """<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>BehaviorDrift Report — {entity_id}</title>
<style>
  body {{ font-family: -apple-system, Segoe UI, Arial, sans-serif; max-width: 820px;
          margin: 40px auto; padding: 0 20px; color: #1a1a2e; background: #fafafa; }}
  h1 {{ font-size: 1.6rem; margin-bottom: 4px; }}
  .subtitle {{ color: #666; margin-bottom: 24px; }}
  .summary {{ display: flex; gap: 16px; margin-bottom: 28px; }}
  .stat {{ background: #fff; border: 1px solid #e4e4e8; border-radius: 8px; padding: 14px 18px; flex: 1; }}
  .stat .n {{ font-size: 1.6rem; font-weight: 700; color: #1E2761; }}
  .stat .label {{ font-size: 0.8rem; color: #777; }}
  .week {{ background: #fff; border: 1px solid #e4e4e8; border-radius: 8px; padding: 16px 20px; margin-bottom: 12px; }}
  .week.flagged {{ border-left: 4px solid #d9534f; }}
  .week.normal {{ border-left: 4px solid #5cb85c; }}
  .week.insufficient_history {{ border-left: 4px solid #ccc; opacity: 0.6; }}
  .week h3 {{ margin: 0 0 6px 0; font-size: 1rem; }}
  .status {{ font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.03em; padding: 2px 8px;
             border-radius: 10px; display: inline-block; margin-left: 8px; }}
  .status.flagged {{ background: #fdecea; color: #d9534f; }}
  .status.normal {{ background: #eaf7ea; color: #5cb85c; }}
  .status.insufficient_history {{ background: #f0f0f0; color: #999; }}
  .explanation {{ margin-top: 10px; font-size: 0.92rem; line-height: 1.5; white-space: pre-line; }}
  .backend-tag {{ font-size: 0.7rem; color: #999; margin-top: 6px; }}
  code {{ background: #f0f0f2; padding: 1px 5px; border-radius: 4px; font-size: 0.85em; }}
</style>
</head>
<body>
  <h1>BehaviorDrift Report</h1>
  <div class="subtitle">Entity: <code>{entity_id}</code></div>

  <div class="summary">
    <div class="stat"><div class="n">{total_weeks}</div><div class="label">Weeks analyzed</div></div>
    <div class="stat"><div class="n">{flagged_weeks}</div><div class="label">Weeks flagged</div></div>
    <div class="stat"><div class="n">{insufficient}</div><div class="label">Baseline warm-up</div></div>
  </div>

  {weeks_html}
</body>
</html>
"""

WEEK_TEMPLATE = """
<div class="week {status}">
  <h3>{week} <span class="status {status}">{status_label}</span></h3>
  {body}
</div>
"""


def render_html(report: dict) -> str:
    weeks_html = []
    for w in report["weeks"]:
        status = w["status"]
        status_label = {"flagged": "Drift Flagged", "normal": "Normal",
                         "insufficient_history": "Building Baseline"}[status]
        body = ""
        if status == "flagged":
            score_line = ""
            if w.get("anomaly_score") is not None:
                score_line = f'<div class="backend-tag">Isolation Forest anomaly score: {html.escape(str(w["anomaly_score"]))}</div>'
            body = score_line + f'<div class="explanation">{html.escape(w["explanation"])}</div>'
            if w.get("commit_messages"):
                msgs = "".join(f"<li>{html.escape(m)}</li>" for m in w["commit_messages"][:5])
                body += f'<div class="explanation"><strong>Commit evidence:</strong><ul>{msgs}</ul></div>'
            body += f'<div class="backend-tag">explanation generated by: {html.escape(w["explanation_backend"])}</div>'
        elif status == "normal":
            body = "<div class=\"explanation\">Within normal historical range for this entity.</div>"
        else:
            body = "<div class=\"explanation\">Not enough prior weeks yet to establish a reliable baseline.</div>"

        weeks_html.append(WEEK_TEMPLATE.format(week=html.escape(w["week"]), status=status,
                                                 status_label=status_label, body=body))

    return HTML_TEMPLATE.format(
        entity_id=html.escape(report["entity_id"]),
        total_weeks=report["summary"]["total_weeks"],
        flagged_weeks=report["summary"]["flagged_weeks"],
        insufficient=report["summary"]["insufficient_history_weeks"],
        weeks_html="\n".join(weeks_html),
    )


def save_html_report(report: dict, path: str):
    html = render_html(report)
    with open(path, "w") as f:
        f.write(html)
    return path
